/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.*;
import static java.lang.Double.valueOf;

/**
 * @author M3ksyk (m3ksyk@gmail.com)
 */
public class Menu extends javax.swing.JFrame {

    private final Controller controller = new Controller(this);

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        calculateIBUButton = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        masaChmielu = new javax.swing.JTextField();
        alfaKwasy = new javax.swing.JTextField();
        utylizacja = new javax.swing.JTextField();
        objBrzeczki = new javax.swing.JTextField();
        ibuResultField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        obliczChmiel = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        ibu = new javax.swing.JTextField();
        objBrzeczki1 = new javax.swing.JTextField();
        alfaKwasy1 = new javax.swing.JTextField();
        utylizacja1 = new javax.swing.JTextField();
        hopsResultField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        czasPasteryzacji = new javax.swing.JTextField();
        temperaturaPasteryzacji = new javax.swing.JTextField();
        pasteurizationResultField = new javax.swing.JTextField();
        obliczPasteryzacje = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        obliczWydajnoscWarzelni = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        breweryEfficiencyResultField = new javax.swing.JTextField();
        zasyp = new javax.swing.JTextField();
        ekstrakt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        obliczWydajnoscZacieru = new javax.swing.JButton();
        ekstrakt1 = new javax.swing.JTextField();
        ekstraktTeor = new javax.swing.JTextField();
        mashEfficiencyResultField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        obliczOdfermentowanie = new javax.swing.JButton();
        attenuationResultField = new javax.swing.JTextField();
        blgKonc = new javax.swing.JTextField();
        blgPocz = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        obliczWode = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Moc = new javax.swing.JTextField();
        wydajnosc = new javax.swing.JTextField();
        czas = new javax.swing.JTextField();
        waterResultField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        obliczCzas = new javax.swing.JButton();
        tempPocz = new javax.swing.JTextField();
        tempKonc = new javax.swing.JTextField();
        objetosc = new javax.swing.JTextField();
        moc1 = new javax.swing.JTextField();
        wydajnosc1 = new javax.swing.JTextField();
        timeResultField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        obliczEnergie = new javax.swing.JButton();
        moc2 = new javax.swing.JTextField();
        czas2 = new javax.swing.JTextField();
        energyResultField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator piwowarski");

        jPanel1.setName("IBU");

        jLabel31.setText("masa chmielu [g]");

        jLabel32.setText("AA [%]");

        jLabel33.setText("Utylizacja [%]");

        jLabel34.setText("V brzeczki [L]");

        calculateIBUButton.setText("Oblicz");

        jLabel35.setText("IBU");

        calculateIBUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczIBUActionPerformed(evt);
            }
        });

        masaChmielu.setName("masaChmielu");





        ibuResultField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel35)
                                        .addComponent(calculateIBUButton)
                                        .addComponent(jLabel34)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel31))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ibuResultField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(objBrzeczki)
                                        .addComponent(utylizacja)
                                        .addComponent(alfaKwasy)
                                        .addComponent(masaChmielu))
                                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel31)
                                        .addComponent(masaChmielu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel32)
                                        .addComponent(alfaKwasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33)
                                        .addComponent(utylizacja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel34)
                                        .addComponent(objBrzeczki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculateIBUButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel35)
                                        .addComponent(ibuResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(72, Short.MAX_VALUE))
        );

        masaChmielu.getAccessibleContext().setAccessibleName("masaChmielu");

        jTabbedPane1.addTab("IBU", jPanel1);

        jPanel2.setName("ilość Chmielu"); // NOI18N

        jLabel26.setText("IBU");

        jLabel27.setText("V brzeczki [L]");

        jLabel28.setText("AA [%]");

        jLabel29.setText("utylizacja [%]");

        obliczChmiel.setText("Oblicz");
        obliczChmiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczChmielActionPerformed(evt);
            }
        });

        jLabel30.setText("ilosc chmielu [g]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addComponent(obliczChmiel)
                                        .addComponent(jLabel30))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(utylizacja1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(alfaKwasy1)
                                                .addComponent(objBrzeczki1)
                                                .addComponent(ibu))
                                        .addComponent(hopsResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(objBrzeczki1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28)
                                        .addComponent(alfaKwasy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel29)
                                        .addComponent(utylizacja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(obliczChmiel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel30)
                                        .addComponent(hopsResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ilość Chmielu", jPanel2);

        jPanel3.setName("pasteryzacja"); // NOI18N

        jLabel1.setText("Czas [min]");

        jLabel2.setText("Temperatura [degC]");

        jLabel3.setText("Jednostki pasteryzacja");

        pasteurizationResultField.setMaximumSize(new java.awt.Dimension(214, 2147483647));


        obliczPasteryzacje.setText("Oblicz");
        obliczPasteryzacje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczPasteryzacjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel3)
                                        .addComponent(obliczPasteryzacje)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pasteurizationResultField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(temperaturaPasteryzacji)
                                        .addComponent(czasPasteryzacji))
                                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(czasPasteryzacji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(temperaturaPasteryzacji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(obliczPasteryzacje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(pasteurizationResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("pasteryzacja", jPanel3);

        jPanel4.setName("wyd warzelni"); // NOI18N

        jLabel23.setText("ekstrakt [g]");

        jLabel24.setText("zasyp [g]");

        obliczWydajnoscWarzelni.setText("Oblicz");
        obliczWydajnoscWarzelni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczWydajnoscWarzelniActionPerformed(evt);
            }
        });

        jLabel25.setText("wydajnosc");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(obliczWydajnoscWarzelni)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel23))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(breweryEfficiencyResultField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(zasyp)
                                        .addComponent(ekstrakt))
                                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(ekstrakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(zasyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(obliczWydajnoscWarzelni)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25)
                                        .addComponent(breweryEfficiencyResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("wyd warzelni", jPanel4);

        jPanel5.setName("wyd zacieru");

        jLabel20.setText("ekstrakt [g]");

        jLabel21.setText("ekstrakt teor [g]");

        jLabel22.setText("wydajnosc");

        obliczWydajnoscZacieru.setText("Oblicz");
        obliczWydajnoscZacieru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczWydajnoscZacieruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(obliczWydajnoscZacieru)
                                .addGap(89, 237, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel22))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ekstraktTeor)
                                                        .addComponent(ekstrakt1)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mashEfficiencyResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(94, 94, 94))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(ekstrakt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(ekstraktTeor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obliczWydajnoscZacieru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(mashEfficiencyResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("wyd zacieru", jPanel5);

        jPanel6.setName("odfermentowanie");

        jLabel17.setText("BLG p");

        jLabel18.setText("BLG k");

        jLabel19.setText("Odfermentowanie");

        obliczOdfermentowanie.setText("Oblicz");
        obliczOdfermentowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.calculateAttenuationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel19)
                                        .addComponent(obliczOdfermentowanie)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel17))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(attenuationResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(blgKonc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(blgPocz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(blgPocz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(blgKonc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(obliczOdfermentowanie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(attenuationResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("odfermentowanie", jPanel6);

        jPanel7.setName("woda odpar");

        jLabel13.setText("Moc [W]");

        jLabel14.setText("Wydajnosc");

        jLabel15.setText("Czas [h]");

        obliczWode.setText("Oblicz");
        obliczWode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczWodeActionPerformed(evt);
            }
        });

        jLabel16.setText("odparowana woda [L]");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(obliczWode)
                                        .addComponent(jLabel16))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(czas, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(wydajnosc)
                                                .addComponent(Moc))
                                        .addComponent(waterResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(Moc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(wydajnosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(czas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obliczWode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(waterResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("woda odpar", jPanel7);

        jPanel8.setName("czas Grzania");

        jLabel7.setText("Tp [degC]");

        jLabel8.setText("Tk [degC]");

        jLabel9.setText("obj [L]");

        jLabel10.setText("moc [W]");

        jLabel11.setText("wydajnosc");

        jLabel12.setText("Czas");

        obliczCzas.setText("Oblicz");
        obliczCzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczCzasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(obliczCzas)
                                        .addComponent(jLabel12))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(moc1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(tempKonc)
                                        .addComponent(tempPocz)
                                        .addComponent(objetosc)
                                        .addComponent(wydajnosc1)
                                        .addComponent(timeResultField))
                                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(tempPocz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(tempKonc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(objetosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(moc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(wydajnosc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obliczCzas)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel12))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(timeResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("czas Grzania", jPanel8);

        jPanel9.setName("energia"); // NOI18N

        jLabel4.setText("Moc [W]");

        jLabel5.setText("Czas [h]");

        jLabel6.setText("Energia [kWh]");

        obliczEnergie.setText("Oblicz");
        obliczEnergie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.obliczEnergieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel6)
                                        .addComponent(obliczEnergie)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(moc2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(czas2)
                                        .addComponent(energyResultField))
                                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(moc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(czas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(obliczEnergie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(energyResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("energia", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }

//    private void obliczPasteryzacjeActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczPasteryzacjeActionPerformed(evt);
//    }
//
//    private void obliczEnergieActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczEnergieActionPerformed(evt);
//    }
//
//    private void obliczCzasActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczCzasActionPerformed(evt);
//    }
//
//    private void obliczWydajnoscZacieruActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczWydajnoscZacieruActionPerformed(evt);
//    }
//
//    private void obliczWydajnoscWarzelniActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczWydajnoscWarzelniActionPerformed(evt);
//    }
//
//    private void obliczWodeActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczWodeActionPerformed(evt);
//    }
//
//    private void obliczIBUActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczIBUActionPerformed(evt);
//    }
//
//    private void obliczChmielActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.obliczChmielActionPerformed(evt);
//    }

//    private void calculateAttenuationActionPerformed(java.awt.event.ActionEvent evt) {
//        controller.calculateAttenuationActionPerformed(evt);
//    }

    /**
     * variables and fields declaration. DO NOT MODIFY
     * @param args the command line arguments
     */

    private double ibuResult;
    private double hopResult;
    private double breweryEfficiencyResult;
    private double waterResult;
    private int attenuationResult;
    private int pasteurizationResult;
    private int mashEfficiencyResult;
    private int energyResult;
    private int timeResult;

    private javax.swing.JTextField hopsResultField;
    private javax.swing.JTextField Moc;
    private javax.swing.JTextField alfaKwasy;
    private javax.swing.JTextField alfaKwasy1;
    private javax.swing.JTextField blgKonc;
    private javax.swing.JTextField blgPocz;
    private javax.swing.JTextField czas;
    private javax.swing.JTextField czas2;
    private javax.swing.JTextField czasPasteryzacji;
    private javax.swing.JTextField timeResultField;
    private javax.swing.JTextField ekstrakt;
    private javax.swing.JTextField ekstrakt1;
    private javax.swing.JTextField ekstraktTeor;
    private javax.swing.JTextField energyResultField;
    private javax.swing.JTextField ibu;
    private javax.swing.JTextField ibuResultField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField pasteurizationResultField;
    private javax.swing.JTextField masaChmielu;
    private javax.swing.JTextField moc1;
    private javax.swing.JTextField moc2;
    private javax.swing.JTextField objBrzeczki;
    private javax.swing.JTextField objBrzeczki1;
    private javax.swing.JTextField objetosc;
    private javax.swing.JButton obliczChmiel;
    private javax.swing.JButton obliczCzas;
    private javax.swing.JButton obliczEnergie;
    private javax.swing.JButton calculateIBUButton;
    private javax.swing.JButton obliczOdfermentowanie;
    private javax.swing.JButton obliczPasteryzacje;
    private javax.swing.JButton obliczWode;
    private javax.swing.JButton obliczWydajnoscWarzelni;
    private javax.swing.JButton obliczWydajnoscZacieru;
    private javax.swing.JTextField attenuationResultField;
    private javax.swing.JTextField waterResultField;
    private javax.swing.JTextField tempKonc;
    private javax.swing.JTextField tempPocz;
    private javax.swing.JTextField temperaturaPasteryzacji;
    private javax.swing.JTextField utylizacja;
    private javax.swing.JTextField utylizacja1;
    private javax.swing.JTextField wydajnosc;
    private javax.swing.JTextField wydajnosc1;
    private javax.swing.JTextField breweryEfficiencyResultField;
    private javax.swing.JTextField mashEfficiencyResultField;
    private javax.swing.JTextField zasyp;

    public double getFieldValue(JTextField field) {

        return controller.getFieldValue(field);
    }

    public double getHopMass() {
        return controller.getFieldValue(masaChmielu);
    }

    public double getPasteurizationTime() {
        return controller.getFieldValue(czasPasteryzacji);
    }

    public double getTheorExtract() {
        return controller.getFieldValue(ekstraktTeor);
    }


    public double getPractExtract() {
        return controller.getFieldValue(ekstrakt1);
    }

    public double getExtract() {
        return controller.getFieldValue(ekstrakt);
    }

    public double getUtilization1() {
        return controller.getFieldValue(utylizacja1);
    }

    public double getAlphaAcids1() {
        return controller.getFieldValue(alfaKwasy1);
    }

    public double getWortVolume1() {
        return controller.getFieldValue(objBrzeczki1);
    }

    public double getIb() {
        return controller.getFieldValue(ibu);
    }

    public double getMaltMass() {
        return controller.getFieldValue(zasyp);
    }

    public double getBlgK() {
        return controller.getFieldValue(blgKonc);
    }

    public double getBlgP() {
        return controller.getFieldValue(blgPocz);
    }

    public double getAlphaAcids() {
        return controller.getFieldValue(alfaKwasy);
    }

    public double getUtilization() {
        return controller.getFieldValue(utylizacja);
    }

    public double getWortVolume() {
        return controller.getFieldValue(objBrzeczki);
    }

    public double getTime() {
        return controller.getFieldValue(czas);
    }

    public double getPower() {
        return controller.getFieldValue(Moc);
    }

    public double getEfficiency1() {
        return controller.getFieldValue(wydajnosc1);
    }

    public double getPower1() {
        return controller.getFieldValue(moc1);
    }

    public double getVolume() {
        return controller.getFieldValue(objetosc);
    }

    public double getTk() {
        return controller.getFieldValue(tempKonc);
    }

    public double getTp() {
        return controller.getFieldValue(tempPocz);
    }

    public double getTime2() {
        return controller.getFieldValue(czas2);
    }

    public double getPower2() {
        return controller.getFieldValue(moc2);
    }

    public double getTempPas() {
        return controller.getFieldValue(temperaturaPasteryzacji);
    }

    public double getEfficiency() {
        return controller.getFieldValue(wydajnosc);
    }

    public int getPasteurizationResult() {
        return pasteurizationResult;
    }

    public int getTimeResult() {
        return timeResult;
    }

    public JTextField getWaterResultField() {
        return waterResultField;
    }

    public JTextField getEnergyResultField() {
        return energyResultField;
    }

    public JTextField getAttenuationResultField() {
        return attenuationResultField;
    }

    public JTextField getBreweryEfficiencyResultField() {
        return breweryEfficiencyResultField;
    }

    public JTextField getIbuResultField() {
        return ibuResultField;
    }

    public int getAttenuationResult() {
        return attenuationResult;
    }

    public double getWaterResult() {
        return waterResult;
    }

    public double getBreweryEfficiencyResult() {
        return breweryEfficiencyResult;
    }

    public int getEnergyResult() {
        return energyResult;
    }

    public int getMashEfficiencyResult() {
        return mashEfficiencyResult;
    }

    public JTextField getMashEfficiencyResultField() {
        return mashEfficiencyResultField;
    }

    public double getIbuResult() {
        return ibuResult;
    }

    public double getHopResult() {
        return hopResult;
    }

    public JTextField getHopsResultField() {
        return hopsResultField;
    }

    public JTextField getTimeResultField() {
        return timeResultField;
    }

    public JTextField getPasteurizationResultField() {
        return pasteurizationResultField;
    }


    public void setPasteurizationResult(int pasteurizationResult) {
        this.pasteurizationResult = pasteurizationResult;
    }

    public void setAttenuationResult(int attenuationResult) {
        this.attenuationResult = attenuationResult;
    }

    public void setTimeResult(int timeResult) {
        this.timeResult = timeResult;
    }

    public void setWaterResult(double waterResult) {
        this.waterResult = waterResult;
    }

    public void setBreweryEfficiencyResult(double breweryEfficiencyResult) {
        this.breweryEfficiencyResult = breweryEfficiencyResult;
    }

    public void setEnergyResult(int energyResult) {
        this.energyResult = energyResult;
    }

    public void setMashEfficiencyResult(int mashEfficiencyResult) {
        this.mashEfficiencyResult = mashEfficiencyResult;
    }

    public void setIbuResult(double ibuResult) {
        this.ibuResult = ibuResult;
    }

    public void setHopResult(double hopResult) {
        this.hopResult = hopResult;
    }

}