/*
 kalkulator piwowarski
    prototyp
dostępne funkcjonalności: obliczanie IBU
 */
package calc;

/**
 *
 * @author Mex
 */
public class Calc extends javax.swing.JFrame {

    
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MasaChmielu = new javax.swing.JLabel();
        AlfaKwas = new javax.swing.JLabel();
        Utyl = new javax.swing.JLabel();
        objBrzeczki = new javax.swing.JLabel();
        HopMass = new javax.swing.JFormattedTextField();
        alphaAcid = new javax.swing.JFormattedTextField();
        util = new javax.swing.JFormattedTextField();
        volume = new javax.swing.JFormattedTextField();
        Oblicz = new javax.swing.JButton();
        ibu = new javax.swing.JLabel();
        Result = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MasaChmielu.setText("Masa Chmielu [g]");

        AlfaKwas.setText("AlfaKwasy [%]");

        Utyl.setText("Utylizacja [%]");

        objBrzeczki.setText("obj. Brzeczki [L]");

        Oblicz.setText("Oblicz");
        HopMass.setSize(20,100); 
        alphaAcid.setSize(20,100); 
        util.setSize(20,100);
        volume.setSize(20,100);
        ibu.setText("IBU");
        Result.setSize(20,100);
        jLabel6.setText("obliczanie IBU");

        HopMass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HopMassActionPerformed(evt);
            }
        });
        alphaAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               String alfa = alphaAcid.getText();
            System.out.println(alfa); 
            
            //action event alphaAcidActionPerformed(evt) sie wykrzacza wiec obsluga
            //wlepiona jest tutaj
            a = Double.parseDouble(alfa);
            }
        });
        
        util.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilActionPerformed(evt);
            }
        });
        
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });

        
        Oblicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObliczActionPerformed(evt);
            }
        });

        
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ibu))
                    .addComponent(Utyl)
                    .addComponent(objBrzeczki)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Oblicz))
                    .addComponent(AlfaKwas)
                    .addComponent(MasaChmielu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Result, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(volume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(util, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alphaAcid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HopMass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MasaChmielu)
                        .addGap(18, 18, 18)
                        .addComponent(AlfaKwas)
                        .addGap(18, 18, 18)
                        .addComponent(Utyl)
                        .addGap(27, 27, 27)
                        .addComponent(objBrzeczki))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HopMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alphaAcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(util, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Oblicz)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibu))
                .addContainerGap(48, Short.MAX_VALUE))
        
        );

        pack();
    }// </editor-fold>                        

    private void HopMassActionPerformed(java.awt.event.ActionEvent evt) {                                        
       String masaChmielu = HopMass.getText();
       System.out.println(masaChmielu);
       m = Double.parseDouble(masaChmielu);
    }                                       
    private void alphaAcidPerformed(java.awt.event.ActionEvent evt) {                                       
        String alfa = alphaAcid.getText();
        System.out.println(alfa);
        a = Double.parseDouble(alfa);
    }  
    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String objetosc = volume.getText();
        System.out.println(objetosc);
        v = Double.parseDouble(objetosc);
    }    
    private void utilActionPerformed(java.awt.event.ActionEvent evt) {                                        
       String utylizacja = util.getText();
       System.out.println(utylizacja);
       u = Double.parseDouble(utylizacja);
    }                                       

    private void ObliczActionPerformed(java.awt.event.ActionEvent evt) {                                       
       
        ibuResult = ((m * a * u)/(v * 10));
        System.out.println("" + ibuResult);
        Result.setText("" + ibuResult);

    } 
    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {                                       
         
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    double m, a, v, u, ibuResult;
    private javax.swing.JLabel AlfaKwas;
    private javax.swing.JFormattedTextField HopMass;
    private javax.swing.JLabel MasaChmielu;
    private javax.swing.JButton Oblicz;
    private javax.swing.JFormattedTextField Result;
    private javax.swing.JLabel Utyl;
    private javax.swing.JFormattedTextField alphaAcid;
    private javax.swing.JLabel ibu;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel objBrzeczki;
    private javax.swing.JFormattedTextField util;
    private javax.swing.JFormattedTextField volume;
    // End of variables declaration                   
}
